version: '3'
services:
  jenkins:
    build:
      dockerfile: Dockerfile
      context: docker
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - "jenkins_home:/var/jenkins_home"
      - "./config:/etc/jenkins/config:ro"
    environment:
      CASC_JENKINS_CONFIG: /etc/jenkins/config/jcasc/
    ulimits:
      nofile:
        soft: 122880
        hard: 122880
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:7.12.8
    volumes:
      - "artifactory_data:/var/opt/jfrog/artifactory"
    ports:
      - 8081:8081
      - 8082:8082
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
  agent1:
    build:
      dockerfile: agent.Dockerfile
      context: docker
    entrypoint: bash /usr/local/bin/wait-for-jenkins.sh /usr/local/bin/jenkins-agent
    volumes:
      - "./docker/wait-for-jenkins.sh:/usr/local/bin/wait-for-jenkins.sh"
      - "agent1-workdir:/home/jenkins/agent"
    environment:
      JENKINS_URL: 'http://jenkins:8080'
      JENKINS_SECRET: "@/tmp/secret"
      JENKINS_AGENT_NAME: agent1
    depends_on:
      - jenkins
  agent2:
    build:
      dockerfile: agent.Dockerfile
      context: docker
    entrypoint: bash /usr/local/bin/wait-for-jenkins.sh /usr/local/bin/jenkins-agent
    volumes:
      - "./docker/wait-for-jenkins.sh:/usr/local/bin/wait-for-jenkins.sh"
      - "agent2-workdir:/home/jenkins/agent"
    environment:
      JENKINS_URL: 'http://jenkins:8080'
      JENKINS_SECRET: "@/tmp/secret"
      JENKINS_AGENT_NAME: agent2
    depends_on:
      - jenkins
volumes:
  jenkins_home:
  agent1-workdir:
  agent2-workdir:
  artifactory_data:
