jobs:
  - script: >
      job('seed') {
        scm {
          git {
            remote { url('https://github.com/aokiji/jenkins-casc-poc.git') }
            branches('master')
            extensions {}
          }
        }
        steps {
          jobDsl {
            targets('config/jobs/**/*.groovy')
          }
        }
      }
