jenkins:
  mode: NORMAL
  numExecutors: 1
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          name: Admin
          password: admin
        - id: user
          name: Common user
          password: user
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Jenkins administrators"
            permissions:
              - "Overall/Administer"
            assignments:
              - "admin"
          - name: "readonly"
            description: "Read-only users"
            permissions:
              - "Overall/Read"
              - "Job/Read"
            assignments:
              - "authenticated"
