unclassified:
  globalLibraries:
    libraries:
    - name: "pipeline-library"
      defaultVersion: "master"
      retriever:
        modernSCM:
          scm:
            git:
              remote: "https://github.com/aokiji/jenkins-casc-poc-library"
              traits:
                - "gitBranchDiscovery"
  artifactoryBuilder:
    artifactoryServers:
    - artifactoryUrl: "http://artifactory:8082/artifactory"
      serverId: "artifactory"
      deployerCredentialsConfig:
        username: "admin"
        password: "{AQAAABAAAAAQlET4ykOc1OF/Wba9nHXp/REUkMo4iGoZeMB9Vo8hBgU=}"
  email-ext:
    mailAccount:
      smtpHost: mail-server
      smtpPort: 1025
    defaultSuffix: "@example.com"
  location:
    adminAddress: "jenkins@example.com"
    url: "http://localhost:8080/"
