version: '3'
services:
  agent1:
    build:
      dockerfile: agent.Dockerfile
      context: docker
    entrypoint: bash /usr/local/bin/wait-for-jenkins.sh /usr/local/bin/jenkins-agent
    volumes:
      - "./docker/wait-for-jenkins.sh:/usr/local/bin/wait-for-jenkins.sh"
      - "agent1-workdir:/home/jenkins/agent"
    environment:
      JENKINS_URL: 'http://jenkins:8080'
      JENKINS_SECRET: "@/tmp/secret"
      JENKINS_AGENT_NAME: agent1
    depends_on:
      - jenkins
volumes:
  agent1-workdir:
