version: '3'
services:
  agent2:
    image: jenkins/inbound-agent
    entrypoint: bash /usr/local/bin/wait-for-jenkins.sh /usr/local/bin/jenkins-agent
    volumes:
      - "./docker/wait-for-jenkins.sh:/usr/local/bin/wait-for-jenkins.sh"
      - "agent2-workdir:/home/jenkins/agent"
    environment:
      JENKINS_URL: 'http://jenkins:8080'
      JENKINS_SECRET: "@/tmp/secret"
      JENKINS_AGENT_NAME: agent2
    depends_on:
      - jenkins
volumes:
  agent2-workdir:
